/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AsistenciaCurso;

import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author aleja
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    CardLayout layout;
    private PanelGestionEstudiantes panelGestionEstudiantes;

    public Ventana() {
        initComponents();

        // SIA-11: Cargar datos al iniciar la interfaz gráfica
        Main.listaGlobal = GestorArchivos.cargarEstudiantes();

        // SIA-11: Guardar al cerrar la ventana
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                GestorArchivos.guardarEstudiantes(Main.listaGlobal);
            }
        });

        layout = new CardLayout();
        panelContenedor.setLayout(layout);

        panelGestionEstudiantes = new PanelGestionEstudiantes(this);

        panelContenedor.add(new Menu(this), "menu");
        panelContenedor.add(new IngresoEstudiante(this), "estudiantes");
        panelContenedor.add(panelGestionEstudiantes, "gestionEstudiantes");
        panelContenedor.add(new PanelAsistencias(this), "asistencias");
    }

    public void cambiarVista(String nombre) {
        layout.show(panelContenedor, nombre);
    }

    /** Refresca la tabla del panel de gestión de estudiantes al navegar a él. */
    public void refrescarPanelEstudiantes() {
        panelGestionEstudiantes.cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
                panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 511, Short.MAX_VALUE));
        panelContenedorLayout.setVerticalGroup(
                panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 338, Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
